// <auto-generated />
using System;
using BusinessLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BusinessLayer.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("BusinessLayer.Model.Leverancier", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("LEVERANCIER_ID")
                        .UseIdentityColumn();

                    b.Property<DateTime>("AutoTimeCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("AUTO_TIME_CREATION")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("MaatschappelijkeZetel")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MAATSCHAPPELIJKE_ZETEL");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("NAAM");

                    b.Property<decimal>("PrijsKHW")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PRIJS");

                    b.Property<DateTime>("PublicatiebeslissingInBelGischStaatsblad")
                        .HasColumnType("datetime2")
                        .HasColumnName("PUBLICATIEBESLISSING_IN_BELGIE");

                    b.Property<DateTime>("ToekenningLeveringvergunning")
                        .HasColumnType("datetime2")
                        .HasColumnName("TOEKENNING_LEVERINGVERGUNNING");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Naam" }, "IX_LEVERANCIER_NAME");

                    b.ToTable("LEVERANCIER");
                });

            modelBuilder.Entity("BusinessLayer.Model.Leverancier", b =>
                {
                    b.HasOne("BusinessLayer.Model.Leverancier", "leverancier")
                        .WithMany("_Leveranciel")
                        .HasForeignKey("Id")
                        .HasConstraintName("FK_LEVERANCIER")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("leverancier");
                });

            modelBuilder.Entity("BusinessLayer.Model.Leverancier", b =>
                {
                    b.Navigation("_Leveranciel");
                });
#pragma warning restore 612, 618
        }
    }
}
